from new_routers.auth_router import router as auth_router
from new_routers.user_router import router as user_router
from new_routers.project_router import router as project_router
from new_routers.task_router import router as task_router
from new_routers.milestone_router import router as milestone_router
from new_routers.participation_request_router import router as participation_request_router 
from new_routers.schedule_router import router as schedule_router
from new_routers.notification_router import router as notification_router
from new_routers.channel_router import router as channel_router
from new_routers.chat_router import router as chat_router
from new_routers.video_call_router import router as video_call_router
from new_routers.voice_call_router import router as voice_call_router
