name: CI & Deploy FastAPI to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      actions: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          DATABASE_URL: "sqlite:///./test.db"
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q

      - name: Create GitHub Deployment
        id: deployment
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/{owner}/{repo}/deployments
          mediaType: application/vnd.github.v3+json
          ref: ${{ github.sha }}
          environment: production

      - name: Trigger Render Deploy
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d3gisdvfte5s73c6obl0" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Accept: application/json"

      - name: Mark deployment as success
        uses: octokit/request-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: POST /repos/{owner}/{repo}/deployments/{deployment_id}/statuses
          deployment_id: ${{ steps.deployment.outputs.id }}
          state: success
          mediaType: application/vnd.github.v3+json