name: CI & Deploy FastAPI to Render

on:
  push:
    branches:
      - main   # 배포하고 싶은 브랜치

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Python 세팅
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. 의존성 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. 테스트 실행
      - name: Run tests
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q

      # 5. GitHub Deployment 생성
      - name: Create GitHub Deployment
        id: deployment
        uses: octokit/request-action@v5
        with:
          route: POST /repos/{owner}/{repo}/deployments
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          ref: ${{ github.sha }}
          environment: production
          required_contexts: []

      # 6. Render 배포 트리거
      - name: Trigger Render Deploy
        run: |
          curl -X POST "https://api.render.com/deploy/srv-d3gisdvfte5s73c6obl0" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Accept: application/json"

      # 7. Deployment 성공 상태 업데이트
      - name: Mark deployment as success
        uses: octokit/request-action@v5
        with:
          route: PATCH /repos/{owner}/{repo}/deployments/{deployment_id}/statuses
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          deployment_id: ${{ steps.deployment.outputs.id }}
          state: success